name: menu
favicon: null
layout_spectrum: 0.8735406878404319
typography_spectrum: 0.07547517912462354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9639003006741405
  lightness: 0.09638677327893674
  saturation: 0.8976350200828165
  rhythmicContrast: 0.27349551068618894
purpose: []
